### ISSUE TITLE
Refactor: Use the regular google uuid as the main type in Sqlc

### ISSUE THREAD

**Issue by cappuccinocosmico** [mycorrhiza-inc/kessler#253]
Apparently you can do stuff like this:
```yaml
version: "2"
sql:
- schema: "postgresql/schema.sql"
  queries: "postgresql/query.sql"
  engine: "postgresql"
  gen:
    go: 
      package: "authors"
      out: "db"
      sql_package: "pgx/v5"
      overrides:
        - db_type: "uuid"
          go_type:
            import: "github.com/google/uuid"
            type: "UUID"
```
in the sqlc config, and absolutely elminate all the casting between types we do, might be a good weekend project or something.
